// Mocks generated by Mockito 5.4.6 from annotations
// in fin_plus/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fin_plus/data/repositories/simulation_repository.dart' as _i3;
import 'package:fin_plus/data/services/DatabaseService.dart' as _i2;
import 'package:fin_plus/domain/models/simulation_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SimulationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSimulationRepository extends _i1.Mock
    implements _i3.SimulationRepository {
  MockSimulationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get dbService =>
      (super.noSuchMethod(
            Invocation.getter(#dbService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#dbService),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i4.Future<void> saveSimulation(_i5.InvestmentSimulation? simulation) =>
      (super.noSuchMethod(
            Invocation.method(#saveSimulation, [simulation]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.InvestmentSimulation>> getAllSimulations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSimulations, []),
            returnValue: _i4.Future<List<_i5.InvestmentSimulation>>.value(
              <_i5.InvestmentSimulation>[],
            ),
          )
          as _i4.Future<List<_i5.InvestmentSimulation>>);
}
