// Mocks generated by Mockito 5.4.6 from annotations
// in fin_plus/test/transactions_pae_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i3;

import 'package:fin_plus/models/category.dart' as _i7;
import 'package:fin_plus/models/transaction_data.dart' as _i5;
import 'package:fin_plus/models/wallet_model.dart' as _i8;
import 'package:fin_plus/ui/dashboard/dashboard_viewmodel.dart' as _i6;
import 'package:fin_plus/ui/transactions/transactions_viewmodel.dart' as _i4;
import 'package:fl_chart/fl_chart.dart' as _i11;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTextEditingController_0 extends _i1.SmartFake
    implements _i2.TextEditingController {
  _FakeTextEditingController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTabController_1 extends _i1.SmartFake implements _i2.TabController {
  _FakeTabController_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeColor_3 extends _i1.SmartFake implements _i3.Color {
  _FakeColor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionViewModel extends _i1.Mock
    implements _i4.TransactionViewModel {
  MockTransactionViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TextEditingController get descriptionController =>
      (super.noSuchMethod(
            Invocation.getter(#descriptionController),
            returnValue: _FakeTextEditingController_0(
              this,
              Invocation.getter(#descriptionController),
            ),
          )
          as _i2.TextEditingController);

  @override
  _i2.TextEditingController get amountController =>
      (super.noSuchMethod(
            Invocation.getter(#amountController),
            returnValue: _FakeTextEditingController_0(
              this,
              Invocation.getter(#amountController),
            ),
          )
          as _i2.TextEditingController);

  @override
  _i2.TabController get tabController =>
      (super.noSuchMethod(
            Invocation.getter(#tabController),
            returnValue: _FakeTabController_1(
              this,
              Invocation.getter(#tabController),
            ),
          )
          as _i2.TabController);

  @override
  bool get isEditMode =>
      (super.noSuchMethod(Invocation.getter(#isEditMode), returnValue: false)
          as bool);

  @override
  _i5.TransactionType get currentType =>
      (super.noSuchMethod(
            Invocation.getter(#currentType),
            returnValue: _i5.TransactionType.income,
          )
          as _i5.TransactionType);

  @override
  DateTime get selectedDate =>
      (super.noSuchMethod(
            Invocation.getter(#selectedDate),
            returnValue: _FakeDateTime_2(
              this,
              Invocation.getter(#selectedDate),
            ),
          )
          as DateTime);

  @override
  _i4.Repetition get repetition =>
      (super.noSuchMethod(
            Invocation.getter(#repetition),
            returnValue: _i4.Repetition.none,
          )
          as _i4.Repetition);

  @override
  _i6.ViewState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6.ViewState.idle,
          )
          as _i6.ViewState);

  @override
  List<_i7.Category> get availableCategories =>
      (super.noSuchMethod(
            Invocation.getter(#availableCategories),
            returnValue: <_i7.Category>[],
          )
          as List<_i7.Category>);

  @override
  List<_i8.Wallet> get availableWallets =>
      (super.noSuchMethod(
            Invocation.getter(#availableWallets),
            returnValue: <_i8.Wallet>[],
          )
          as List<_i8.Wallet>);

  @override
  _i3.Color get headerColor =>
      (super.noSuchMethod(
            Invocation.getter(#headerColor),
            returnValue: _FakeColor_3(this, Invocation.getter(#headerColor)),
          )
          as _i3.Color);

  @override
  String get formattedDate =>
      (super.noSuchMethod(
            Invocation.getter(#formattedDate),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#formattedDate),
            ),
          )
          as String);

  @override
  set tabController(_i2.TabController? _tabController) => super.noSuchMethod(
    Invocation.setter(#tabController, _tabController),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? _errorMessage) => super.noSuchMethod(
    Invocation.setter(#errorMessage, _errorMessage),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setTabController(_i2.TabController? controller) => super.noSuchMethod(
    Invocation.method(#setTabController, [controller]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> loadInitialData() =>
      (super.noSuchMethod(
            Invocation.method(#loadInitialData, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> selectDate(_i2.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#selectDate, [context]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void selectCategory(_i7.Category? category) => super.noSuchMethod(
    Invocation.method(#selectCategory, [category]),
    returnValueForMissingStub: null,
  );

  @override
  void selectWallet({required bool? isSource, required String? walletName}) =>
      super.noSuchMethod(
        Invocation.method(#selectWallet, [], {
          #isSource: isSource,
          #walletName: walletName,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void setRepetition(int? index) => super.noSuchMethod(
    Invocation.method(#setRepetition, [index]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<bool> saveOrUpdateTransaction() =>
      (super.noSuchMethod(
            Invocation.method(#saveOrUpdateTransaction, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DashboardViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardViewModel extends _i1.Mock
    implements _i6.DashboardViewModel {
  MockDashboardViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ViewState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6.ViewState.idle,
          )
          as _i6.ViewState);

  @override
  double get totalBalance =>
      (super.noSuchMethod(Invocation.getter(#totalBalance), returnValue: 0.0)
          as double);

  @override
  double get monthlyExpenses =>
      (super.noSuchMethod(Invocation.getter(#monthlyExpenses), returnValue: 0.0)
          as double);

  @override
  List<_i11.FlSpot> get balanceEvolution =>
      (super.noSuchMethod(
            Invocation.getter(#balanceEvolution),
            returnValue: <_i11.FlSpot>[],
          )
          as List<_i11.FlSpot>);

  @override
  List<DateTime> get balanceEvolutionDates =>
      (super.noSuchMethod(
            Invocation.getter(#balanceEvolutionDates),
            returnValue: <DateTime>[],
          )
          as List<DateTime>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> fetchDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchDashboardData, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
