// Mocks generated by Mockito 5.4.6 from annotations
// in fin_plus/test/viewmodels/expenses_list_viewodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fin_plus/data/repositories/TransactionRepository.dart' as _i4;
import 'package:fin_plus/data/services/DatabaseService.dart' as _i2;
import 'package:fin_plus/domain/models/report_data_model.dart' as _i3;
import 'package:fin_plus/models/transaction_data.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReportData_1 extends _i1.SmartFake implements _i3.ReportData {
  _FakeReportData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i4.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get dbService =>
      (super.noSuchMethod(
            Invocation.getter(#dbService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#dbService),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i5.Future<int> addTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [transaction]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<double> getTotalBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalBalance, []),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<_i3.ReportData> getReportData(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReportData, [startDate, endDate]),
            returnValue: _i5.Future<_i3.ReportData>.value(
              _FakeReportData_1(
                this,
                Invocation.method(#getReportData, [startDate, endDate]),
              ),
            ),
          )
          as _i5.Future<_i3.ReportData>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getBalanceEvolution({int? days = 7}) =>
      (super.noSuchMethod(
            Invocation.method(#getBalanceEvolution, [], {#days: days}),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<double> getExpensesForMonth(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesForMonth, [month]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<Map<String, double>> getExpensesByCategoryForMonth(
    DateTime? month,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByCategoryForMonth, [month]),
            returnValue: _i5.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i5.Future<Map<String, double>>);

  @override
  _i5.Future<List<_i6.Transaction>> getTransactionsByMonth(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByMonth, [date]),
            returnValue: _i5.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i5.Future<List<_i6.Transaction>>);

  @override
  _i5.Future<List<_i6.Transaction>> getAllTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactions, []),
            returnValue: _i5.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i5.Future<List<_i6.Transaction>>);

  @override
  _i5.Future<double> getCurrentBalanceForWallet(String? walletName) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentBalanceForWallet, [walletName]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<double> getSumOfIncomesByMonth(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getSumOfIncomesByMonth, [date]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<double> getSumOfExpensesByMonth(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getSumOfExpensesByMonth, [date]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);
}
