// Mocks generated by Mockito 5.4.6 from annotations
// in fin_plus/test/viewmodels/transaction_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i13;

import 'package:fin_plus/data/repositories/category_repository.dart' as _i7;
import 'package:fin_plus/data/repositories/TransactionRepository.dart' as _i4;
import 'package:fin_plus/data/repositories/wallet_repository.dart' as _i9;
import 'package:fin_plus/data/services/DatabaseService.dart' as _i2;
import 'package:fin_plus/domain/models/report_data_model.dart' as _i3;
import 'package:fin_plus/models/category.dart' as _i8;
import 'package:fin_plus/models/transaction_data.dart' as _i6;
import 'package:fin_plus/models/wallet_model.dart' as _i10;
import 'package:fin_plus/ui/dashboard/dashboard_viewmodel.dart' as _i11;
import 'package:fl_chart/fl_chart.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReportData_1 extends _i1.SmartFake implements _i3.ReportData {
  _FakeReportData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i4.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get dbService =>
      (super.noSuchMethod(
            Invocation.getter(#dbService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#dbService),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i5.Future<int> addTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [transaction]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<double> getTotalBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalBalance, []),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<_i3.ReportData> getReportData(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReportData, [startDate, endDate]),
            returnValue: _i5.Future<_i3.ReportData>.value(
              _FakeReportData_1(
                this,
                Invocation.method(#getReportData, [startDate, endDate]),
              ),
            ),
          )
          as _i5.Future<_i3.ReportData>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getBalanceEvolution({int? days = 7}) =>
      (super.noSuchMethod(
            Invocation.method(#getBalanceEvolution, [], {#days: days}),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<double> getExpensesForMonth(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesForMonth, [month]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<Map<String, double>> getExpensesByCategoryForMonth(
    DateTime? month,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByCategoryForMonth, [month]),
            returnValue: _i5.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i5.Future<Map<String, double>>);

  @override
  _i5.Future<List<_i6.Transaction>> getTransactionsByMonth(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByMonth, [date]),
            returnValue: _i5.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i5.Future<List<_i6.Transaction>>);

  @override
  _i5.Future<List<_i6.Transaction>> getAllTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactions, []),
            returnValue: _i5.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i5.Future<List<_i6.Transaction>>);

  @override
  _i5.Future<double> getCurrentBalanceForWallet(String? walletName) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentBalanceForWallet, [walletName]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<double> getSumOfIncomesByMonth(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getSumOfIncomesByMonth, [date]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<double> getSumOfExpensesByMonth(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getSumOfExpensesByMonth, [date]),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i7.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get dbService =>
      (super.noSuchMethod(
            Invocation.getter(#dbService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#dbService),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i5.Future<int> addCategory(_i8.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#addCategory, [category]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateCategory(_i8.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [category]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> deleteCategory(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.Category>> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue: _i5.Future<List<_i8.Category>>.value(<_i8.Category>[]),
          )
          as _i5.Future<List<_i8.Category>>);
}

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i9.WalletRepository {
  MockWalletRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get dbService =>
      (super.noSuchMethod(
            Invocation.getter(#dbService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#dbService),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i5.Future<int> addWallet(_i10.Wallet? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#addWallet, [wallet]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateWallet(_i10.Wallet? wallet) =>
      (super.noSuchMethod(
            Invocation.method(#updateWallet, [wallet]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> deleteWallet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWallet, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i10.Wallet>> getAllWallets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWallets, []),
            returnValue: _i5.Future<List<_i10.Wallet>>.value(<_i10.Wallet>[]),
          )
          as _i5.Future<List<_i10.Wallet>>);
}

/// A class which mocks [DashboardViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardViewModel extends _i1.Mock
    implements _i11.DashboardViewModel {
  MockDashboardViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.ViewState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i11.ViewState.idle,
          )
          as _i11.ViewState);

  @override
  double get totalBalance =>
      (super.noSuchMethod(Invocation.getter(#totalBalance), returnValue: 0.0)
          as double);

  @override
  double get monthlyExpenses =>
      (super.noSuchMethod(Invocation.getter(#monthlyExpenses), returnValue: 0.0)
          as double);

  @override
  List<_i12.FlSpot> get balanceEvolution =>
      (super.noSuchMethod(
            Invocation.getter(#balanceEvolution),
            returnValue: <_i12.FlSpot>[],
          )
          as List<_i12.FlSpot>);

  @override
  List<DateTime> get balanceEvolutionDates =>
      (super.noSuchMethod(
            Invocation.getter(#balanceEvolutionDates),
            returnValue: <DateTime>[],
          )
          as List<DateTime>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchDashboardData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
